### ISSUE TITLE
potential nil pointer panic

### ISSUE THREAD

**Issue by DanielQujun** [kubeflow/mpi-operator#274]
Just for Ad-hoctesting, when I delete the section of `Launcher.template.spec` from the `mpijob`  yaml file, `mpi-operator`  panic.
```
E0628 10:09:12.583406  317537 mpi_job_controller.go:1252] Launcher pod does not have any containers in its spec
I0628 10:09:12.583421  317537 mpi_job_controller.go:447] Finished syncing job "default/tensorflow-benchmarks" (116.885µs)
E0628 10:09:12.583476  317537 runtime.go:73] Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)
goroutine 224 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x13b6540, 0xc0003ce340)
        /go/pkg/mod/k8s.io/apimachinery@v0.15.10/pkg/util/runtime/runtime.go:69 +0x7b
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.15.10/pkg/util/runtime/runtime.go:51 +0x82
panic(0x13b6540, 0xc0003ce340)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/kubeflow/mpi-operator/pkg/controllers/v1alpha2.(*MPIJobController).newLauncher(0xc0002dd040, 0xc00020e1a0, 0x7ffec03a9859, 0x23, 0xc0001a6ce0)
        /go/src/github.com/kubeflow/mpi-operator/pkg/controllers/v1alpha2/mpi_job_controller.go:1254 +0x1ba6
github.com/kubeflow/mpi-operator/pkg/controllers/v1alpha2.(*MPIJobController).syncHandler(0xc0002dd040, 0xc000324380, 0x1d, 0x0, 0x0)
        /go/src/github.com/kubeflow/mpi-operator/pkg/controllers/v1alpha2/mpi_job_controller.go:554 +0x94e
github.com/kubeflow/mpi-operator/pkg/controllers/v1alpha2.(*MPIJobController).processNextWorkItem.func1(0xc0002dd040, 0x1269440, 0xc0006fc0a0, 0x0, 0x0)
        /go/src/github.com/kubeflow/mpi-operator/pkg/controllers/v1alpha2/mpi_job_controller.go:422 +0xf6
github.com/kubeflow/mpi-operator/pkg/controllers/v1alpha2.(*MPIJobController).processNextWorkItem(0xc0002dd040, 0x0)
        /go/src/github.com/kubeflow/mpi-operator/pkg/controllers/v1alpha2/mpi_job_controller.go:431 +0x53
github.com/kubeflow/mpi-operator/pkg/controllers/v1alpha2.(*MPIJobController).runWorker(0xc0002dd040)
        /go/src/github.com/kubeflow/mpi-operator/pkg/controllers/v1alpha2/mpi_job_controller.go:383 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000b113a0)
        /go/pkg/mod/k8s.io/apimachinery@v0.15.10/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000b113a0, 0x3b9aca00, 0x0, 0x1, 0xc00015a1e0)
        /go/pkg/mod/k8s.io/apimachinery@v0.15.10/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc000b113a0, 0x3b9aca00, 0xc00015a1e0)
        /go/pkg/mod/k8s.io/apimachinery@v0.15.10/pkg/util/wait/wait.go:88 +0x4d
created by github.com/kubeflow/mpi-operator/pkg/controllers/v1alpha2.(*MPIJobController).Run
        /go/src/github.com/kubeflow/mpi-operator/pkg/controllers/v1alpha2/mpi_job_controller.go:369 +0x317
panic: runtime error: index out of range [0] with length 0 [recovered]
        panic: runtime error: index out of range [0] with length 0

goroutine 224 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.15.10/pkg/util/runtime/runtime.go:58 +0x105
panic(0x13b6540, 0xc0003ce340)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/kubeflow/mpi-operator/pkg/controllers/v1alpha2.(*MPIJobController).newLauncher(0xc0002dd040, 0xc00020e1a0, 0x7ffec03a9859, 0x23, 0xc0001a6ce0)
        /go/src/github.com/kubeflow/mpi-operator/pkg/controllers/v1alpha2/mpi_job_controller.go:1254 +0x1ba6
github.com/kubeflow/mpi-operator/pkg/controllers/v1alpha2.(*MPIJobController).syncHandler(0xc0002dd040, 0xc000324380, 0x1d, 0x0, 0x0)
        /go/src/github.com/kubeflow/mpi-operator/pkg/controllers/v1alpha2/mpi_job_controller.go:554 +0x94e
github.com/kubeflow/mpi-operator/pkg/controllers/v1alpha2.(*MPIJobController).processNextWorkItem.func1(0xc0002dd040, 0x1269440, 0xc0006fc0a0, 0x0, 0x0)
        /go/src/github.com/kubeflow/mpi-operator/pkg/controllers/v1alpha2/mpi_job_controller.go:422 +0xf6
github.com/kubeflow/mpi-operator/pkg/controllers/v1alpha2.(*MPIJobController).processNextWorkItem(0xc0002dd040, 0x0)
        /go/src/github.com/kubeflow/mpi-operator/pkg/controllers/v1alpha2/mpi_job_controller.go:431 +0x53
github.com/kubeflow/mpi-operator/pkg/controllers/v1alpha2.(*MPIJobController).runWorker(0xc0002dd040)
        /go/src/github.com/kubeflow/mpi-operator/pkg/controllers/v1alpha2/mpi_job_controller.go:383 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000b113a0)
        /go/pkg/mod/k8s.io/apimachinery@v0.15.10/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000b113a0, 0x3b9aca00, 0x0, 0x1, 0xc00015a1e0)
        /go/pkg/mod/k8s.io/apimachinery@v0.15.10/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc000b113a0, 0x3b9aca00, 0xc00015a1e0)
        /go/pkg/mod/k8s.io/apimachinery@v0.15.10/pkg/util/wait/wait.go:88 +0x4d
created by github.com/kubeflow/mpi-operator/pkg/controllers/v1alpha2.(*MPIJobController).Run
        /go/src/github.com/kubeflow/mpi-operator/pkg/controllers/v1alpha2/mpi_job_controller.go:369 +0x317
```

 It's not an authentic user case, However, Given that there isn't admission webhook or scheme validation, I think It's worthwhile to add some lines to strengthen our code.

## how-to reproduce
```
apiVersion: kubeflow.org/v1alpha2
kind: MPIJob
metadata:
  name: tensorflow-benchmarks
spec:
  cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec: null
    Worker:
      replicas: 2
      template:
        spec:
          containers:
          - image: mpioperator/tensorflow-benchmarks:latest
            name: tensorflow-benchmarks
  slotsPerWorker: 1
```

**Comment by terrytangyuan** [comment]
Agreed that there's potential to improve usability there. You are welcome to exercise and add handling for these cases.

**Comment by DanielQujun** [comment]
@terrytangyuan Hi, I added a pr, PTAL

**Comment by DanielQujun** [comment]
#275 merged. closing
