### ISSUE TITLE
how can I Launch a multi-node horovod training job with mpi-openrator?

### ISSUE THREAD

**Issue by tingweiwu** [kubeflow/mpi-operator#40]
after I do `kubectl create -f deploy/`
I want a test training jod

As I just 2 node. one 1 GPU , anoher 2 GPUs
I tried examples/tensorflow-benchmarks-imagenet.yaml  with a modified but I get error.
change 
```
spec:
  gpus: 32

```
to
```
spec:
  gpus: 2
```
and error is 
```
# kubectl create -f tensorflow-benchmarks-imagenet.yaml 
The MPIJob "tensorflow-benchmarks-imagenet" is invalid: []: Invalid value: map[string]interface {}{"metadata":map[string]interface {}{"uid":"7eda61e2-a2c7-11e8-80c4-fa163eb0739b", "selfLink":"", "clusterName":"", "name":"tensorflow-benchmarks-imagenet", "namespace":"default", "creationTimestamp":"2018-08-18T09:17:14Z"}, "spec":map[string]interface {}{"template":map[string]interface {}{"spec":map[string]interface {}{"containers":[]interface {}{map[string]interface {}{"name":"tensorflow-benchmarks", "volumeMounts":[]interface {}{map[string]interface {}{"mountPath":"/efs", "name":"efs"}, map[string]interface {}{"name":"models", "mountPath":"/models"}}, "command":[]interface {}{"mpirun", "python", "scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py", "--data_format=NCHW", "--batch_size=256", "--model=resnet50", "--optimizer=momentum", "--variable_update=horovod", "--nodistortions", "--gradient_repacking=8", "--num_epochs=90", "--weight_decay=1e-4", "--data_dir=/efs/imagenet/train", "--use_fp16", "--train_dir=/models/resnet50"}, "image":"mpioperator/tensorflow-benchmarks:latest"}}, "volumes":[]interface {}{map[string]interface {}{"name":"efs", "nfs":map[string]interface {}{"server":"fs-ab134502.efs.us-west-2.amazonaws.com", "path":"/", "readOnly":true}}, map[string]interface {}{"emptyDir":map[string]interface {}{}, "name":"models"}}}}, "gpus":2}, "apiVersion":"kubeflow.org/v1alpha1", "kind":"MPIJob"}: validation failure list:
must validate one and only one schema (oneOf)
must validate one and only one schema (oneOf)
spec.gpus in body should be one of [1 2 4]

```
how can I run examples/tensorflow-benchmarks-imagenet.yaml ？

additionally, I want to test a horovod examples like tensorflow_mnist.py  can I define yaml like this?

```yaml
apiVersion: kubeflow.org/v1alpha1
kind: MPIJob
metadata:
  name: mpijob-horovod
spec:
  replicas: 2
  template:
    spec:
      containers:
      - image: uber/horovod:0.13.10-tf1.9.0-torch0.4.0-py3.5
        command:
          - mpirun 
          - python
          - tensorflow_mnist.py
        imagePullPolicy: IfNotPresent
        name: mpijob-horovod
        resources:
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - mountPath: /examples/MNIST-data-0
          name: datavolume
      restartPolicy: Never
      volumes:
      - hostPath:
        path: /sfs/data/mnist
        type: DirectoryOrCreate
        name: datavolume
```

**Comment by rongou** [comment]
The yaml file you included should work. Did you get any errors from it?

There are basically two ways of running mpi jobs. The first, "simple" approach is to specify `gpus`. For this to work, you need to configure the operator to match your cluster environment. In your case, you need to change `deploy/3-mpi-operator.yaml` to set `--gpus-per-node` to 1.

The second "custom" approach is to specify both `replicas` and gpu limit yourself, which is what you are doing in your yaml file.

**Comment by tingweiwu** [comment]
@rongou Yes. I got some error when I run my yaml file with  horovod example. 
the launcher pod restart 3 times and the errors from laucher pod are as follow:

it may seem like an  connection error?
```
# kubectl logs mpijob-horovod-launcher-dfczv
+ POD_NAME=mpijob-horovod-worker-0
+ shift
+ /opt/kube/kubectl exec mpijob-horovod-worker-0 -- /bin/sh -c     PATH=/usr/local/bin:$PATH ; export PATH ; LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH ; export LD_LIBRARY_PATH ; DYLD_LIBRARY_PATH=/usr/local/lib:$DYLD_LIBRARY_PATH ; export DYLD_LIBRARY_PATH ;   /usr/local/bin/orted -mca ess "env" -mca ess_base_jobid "697106432" -mca ess_base_vpid 1 -mca ess_base_num_procs "3" -mca orte_node_regex "mpijob-horovod-launcher-dfczv,mpijob-horovod-worker-0,mpijob-horovod-worker-1@0(3)" -mca orte_hnp_uri "697106432.0;tcp://172.16.216.225:56858" -mca plm "rsh" -mca plm_rsh_agent "/etc/mpi/kubexec.sh" -mca orte_default_hostfile "/etc/mpi/hostfile" -mca pmix "^s1,s2,cray,isolated"
+ POD_NAME=mpijob-horovod-worker-1
+ shift
+ /opt/kube/kubectl exec mpijob-horovod-worker-1 -- /bin/sh -c     PATH=/usr/local/bin:$PATH ; export PATH ; LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH ; export LD_LIBRARY_PATH ; DYLD_LIBRARY_PATH=/usr/local/lib:$DYLD_LIBRARY_PATH ; export DYLD_LIBRARY_PATH ;   /usr/local/bin/orted -mca ess "env" -mca ess_base_jobid "697106432" -mca ess_base_vpid 2 -mca ess_base_num_procs "3" -mca orte_node_regex "mpijob-horovod-launcher-dfczv,mpijob-horovod-worker-0,mpijob-horovod-worker-1@0(3)" -mca orte_hnp_uri "697106432.0;tcp://172.16.216.225:56858" -mca plm "rsh" -mca plm_rsh_agent "/etc/mpi/kubexec.sh" -mca orte_default_hostfile "/etc/mpi/hostfile" -mca pmix "^s1,s2,cray,isolated"
------------------------------------------------------------
A process or daemon was unable to complete a TCP connection
to another process:
  Local host:    mpijob-horovod-worker-0
  Remote host:   mpijob-horovod-launcher-dfczv
This is usually caused by a firewall on the remote host. Please
check that any firewall (e.g., iptables) has been disabled and
try again.
------------------------------------------------------------
command terminated with exit code 1
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------

```

**Comment by rongou** [comment]
Yeah does look like some kind of connection error. How did you set up your kubernetes cluster? What CNI plugin are you using?

**Comment by tingweiwu** [comment]
@rongou Yes. my kubernetes cluster use calico plugin. the connection error is becuase some of my calico-nodes is not Running. after I fixed this. I run horovod example again.
my `mpijob-horovod-launcher-9h7hw` pod restart again and and I get another error this times.
it seems that error occurs when `read_data_sets('MNIST-data-%d' % hvd.rank())`
this horovod example I have tested on pods with hostnetwork and it works well. 

```
+ POD_NAME=mpijob-horovod-worker-1
+ shift
+ /opt/kube/kubectl exec mpijob-horovod-worker-1 -- /bin/sh -c     PATH=/usr/local/bin:$PATH ; export PATH ; LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH ; export LD_LIBRARY_PATH ; DYLD_LIBRARY_PATH=/usr/local/lib:$DYLD_LIBRARY_PATH ; export DYLD_LIBRARY_PATH ;   /usr/local/bin/orted -mca ess "env" -mca ess_base_jobid "1334378496" -mca ess_base_vpid 2 -mca ess_base_num_procs "3" -mca orte_node_regex "mpijob-horovod-launcher-9h7hw,mpijob-horovod-worker-0,mpijob-horovod-worker-1@0(3)" -mca orte_hnp_uri "1334378496.0;tcp://192.168.170.49:45223" -mca plm "rsh" -mca plm_rsh_agent "/etc/mpi/kubexec.sh" -mca orte_default_hostfile "/etc/mpi/hostfile" -mca pmix "^s1,s2,cray,isolated"
+ POD_NAME=mpijob-horovod-worker-0
+ shift
+ /opt/kube/kubectl exec mpijob-horovod-worker-0 -- /bin/sh -c     PATH=/usr/local/bin:$PATH ; export PATH ; LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH ; export LD_LIBRARY_PATH ; DYLD_LIBRARY_PATH=/usr/local/lib:$DYLD_LIBRARY_PATH ; export DYLD_LIBRARY_PATH ;   /usr/local/bin/orted -mca ess "env" -mca ess_base_jobid "1334378496" -mca ess_base_vpid 1 -mca ess_base_num_procs "3" -mca orte_node_regex "mpijob-horovod-launcher-9h7hw,mpijob-horovod-worker-0,mpijob-horovod-worker-1@0(3)" -mca orte_hnp_uri "1334378496.0;tcp://192.168.170.49:45223" -mca plm "rsh" -mca plm_rsh_agent "/etc/mpi/kubexec.sh" -mca orte_default_hostfile "/etc/mpi/hostfile" -mca pmix "^s1,s2,cray,isolated"
WARNING:tensorflow:From tensorflow_mnist.py:70: read_data_sets (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
WARNING:tensorflow:From tensorflow_mnist.py:70: read_data_sets (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:260: maybe_download (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Please write your own downloading logic.
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:260: maybe_download (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Please write your own downloading logic.
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:262: extract_images (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST-data-0/train-images-idx3-ubyte.gz
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:262: extract_images (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST-data-1/train-images-idx3-ubyte.gz
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:252: _internal_retry.<locals>.wrap.<locals>.wrapped_fn (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Please use urllib or similar directly.
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:252: _internal_retry.<locals>.wrap.<locals>.wrapped_fn (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Please use urllib or similar directly.
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting MNIST-data-0/train-labels-idx1-ubyte.gz
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:267: extract_labels (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.data to implement this functionality.
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting MNIST-data-1/train-labels-idx1-ubyte.gz
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:267: extract_labels (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.data to implement this functionality.
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1260, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tensorflow_mnist.py", line 123, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "tensorflow_mnist.py", line 70, in main
    mnist = learn.datasets.mnist.read_data_sets('MNIST-data-%d' % hvd.rank())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 250, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 270, in read_data_sets
    source_url + TEST_IMAGES)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 250, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 252, in maybe_download
    temp_file_name, _ = urlretrieve_with_retry(source_url)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 250, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 205, in wrapped_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 233, in urlretrieve_with_retry
    return urllib.request.urlretrieve(url, filename)
  File "/usr/lib/python3.5/urllib/request.py", line 188, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1260, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tensorflow_mnist.py", line 123, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "tensorflow_mnist.py", line 70, in main
    mnist = learn.datasets.mnist.read_data_sets('MNIST-data-%d' % hvd.rank())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 250, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 270, in read_data_sets
    source_url + TEST_IMAGES)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 250, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 252, in maybe_download
    temp_file_name, _ = urlretrieve_with_retry(source_url)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 250, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 205, in wrapped_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 233, in urlretrieve_with_retry
    return urllib.request.urlretrieve(url, filename)
  File "/usr/lib/python3.5/urllib/request.py", line 188, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun.real detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[20361,1],0]
  Exit code:    1
--------------------------------------------------------------------------


```


I notice that I also get an host os error 

```
Message from syslogd@bms-bf19-0001 at Aug 20 11:22:51 ...
 kernel:[1990012.689982] unregister_netdevice: waiting for lo to become free. Usage count = 1

```

**Comment by rongou** [comment]
Yeah looks like problem downloading mnist? If you just want to test mpi, you can run something super simple like `mpirun hostname`.

**Comment by tingweiwu** [comment]
@rongou Yes. Just as you said. when I mount mnist data into container so it no need to downloading, I run horovod mnist examples success. Many thanks for your replying

the logs from `launcher`
```
# kubectl logs --tail=10 mpijob-horovod-launcher-t4dws 
INFO:tensorflow:loss = 0.0, step = 8260 (0.533 sec)
INFO:tensorflow:loss = 9.3218034e-07, step = 8270 (0.703 sec)
INFO:tensorflow:loss = 3.4256195e-06, step = 8270 (0.703 sec)
INFO:tensorflow:loss = 0.0, step = 8280 (0.424 sec)
INFO:tensorflow:loss = 8.4557476e-05, step = 8280 (0.425 sec)
INFO:tensorflow:loss = 2.6345043e-07, step = 8290 (0.548 sec)
INFO:tensorflow:loss = 7.867797e-08, step = 8290 (0.549 sec)
INFO:tensorflow:loss = 0.0017644487, step = 8300 (0.575 sec)
INFO:tensorflow:global_step/sec: 18.1632
INFO:tensorflow:loss = 0.0070591937, step = 8300 (0.576 sec)
```

Here is my finally yaml.
As the tensorflow_mnist.py examples read data from `('MNIST-data-%d' % hvd.rank())`. so I mounted the same dir to containers `MNIST-data-0`  and `MNIST-data-1`.   I don't have any better idea about this. 
 
```
apiVersion: kubeflow.org/v1alpha1
kind: MPIJob
metadata:
  name: mpijob-horovod
spec:
  replicas: 2
  template:
    spec:
      containers:
      - image: uber/horovod:0.13.10-tf1.9.0-torch0.4.0-py3.5
        command:
          - mpirun
          - python
          - tensorflow_mnist.py
        imagePullPolicy: IfNotPresent
        name: mpijob-horovod
        resources:
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - mountPath: /examples/MNIST-data-0
          name: datavolume
        - mountPath: /examples/MNIST-data-1
          name: datavolume
      restartPolicy: Never
      volumes:
      - hostPath:
          path: /data/mnist
          type: DirectoryOrCreate
        name: datavolume
```

**Comment by rongou** [comment]
Cool, glad it's working for you now. We can probably use some better documentation. :)
