### ISSUE TITLE
tensorflow-mnist-elastic example failed

### ISSUE THREAD

**Issue by tingweiwu** [kubeflow/mpi-operator#444]
I tried the example [examples/horovod/tensorflow-mnist-elastic.yaml](https://github.com/kubeflow/mpi-operator/blob/master/examples/horovod/tensorflow-mnist-elastic.yaml)

I first deployed mpi-operator by
```
kubectl create -f  deploy/v2beta1/mpi-operator.yaml
kubectl create -f  examples/horovod/tensorflow-mnist-elastic.yaml
```
and I got the error
```
tensorflow-mnist-elastic-launcher-qdngx   0/1     CrashLoopBackOff   4          2m24s
tensorflow-mnist-elastic-worker-0         1/1     Running            0          2m24s
tensorflow-mnist-elastic-worker-1         1/1     Running            0          2m24s

# kubectl logs -n mpi-operator tensorflow-mnist-elastic-launcher-qdngx
Traceback (most recent call last):
  File "/usr/local/bin/horovodrun", line 33, in <module>
    sys.exit(load_entry_point('horovod==0.20.0', 'console_scripts', 'horovodrun')())
  File "/usr/local/lib/python3.7/dist-packages/horovod/runner/launch.py", line 722, in run_commandline
    _run(args)
  File "/usr/local/lib/python3.7/dist-packages/horovod/runner/launch.py", line 710, in _run
    return _run_elastic(args)
  File "/usr/local/lib/python3.7/dist-packages/horovod/runner/launch.py", line 623, in _run_elastic
    gloo_run_elastic(settings, env, args.command)
  File "/usr/local/lib/python3.7/dist-packages/horovod/runner/gloo_run.py", line 322, in gloo_run_elastic
    launch_gloo_elastic(command, exec_command, settings, env, get_common_interfaces, rendezvous)
  File "/usr/local/lib/python3.7/dist-packages/horovod/runner/gloo_run.py", line 287, in launch_gloo_elastic
    driver.wait_for_available_slots(settings.num_proc)
  File "/usr/local/lib/python3.7/dist-packages/horovod/runner/elastic/driver.py", line 160, in wait_for_available_slots
    if current_hosts.count_available_slots() >= min_np and len(current_hosts.available_hosts) >= min_hosts:
  File "/usr/local/lib/python3.7/dist-packages/horovod/runner/elastic/discovery.py", line 71, in count_available_slots
    return sum([self.get_slots(host) for host in self._host_assignment_order])
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

# kubectl get configmap -n mpi-operator tensorflow-mnist-elastic-config  -o yaml
apiVersion: v1
data:
  discover_hosts.sh: |
    #!/bin/sh
    echo tensorflow-mnist-elastic-worker-0.tensorflow-mnist-elastic-worker
    echo tensorflow-mnist-elastic-worker-1.tensorflow-mnist-elastic-worker
  hostfile: |
    tensorflow-mnist-elastic-worker-0.tensorflow-mnist-elastic-worker
    tensorflow-mnist-elastic-worker-1.tensorflow-mnist-elastic-worker
kind: ConfigMap
metadata:
  creationTimestamp: "2021-12-07T06:48:27Z"
  labels:
    app: tensorflow-mnist-elastic
  name: tensorflow-mnist-elastic-config
  namespace: mpi-operator
  ownerReferences:
  - apiVersion: kubeflow.org/v2beta1
    blockOwnerDeletion: true
    controller: true
    kind: MPIJob
    name: tensorflow-mnist-elastic
    uid: ed37f331-f5e7-400b-868d-78576ffe1070
  resourceVersion: "42252316"
  selfLink: /api/v1/namespaces/mpi-operator/configmaps/tensorflow-mnist-elastic-config
  uid: 78c959b2-0f17-4946-bdde-efa6ba5c40e7


```

**Comment by zw0610** [comment]
Unfortunately, v2beta1 does not support elastic training, which we should make it clear to users. Please use [deploy file for v1](https://github.com/kubeflow/mpi-operator/blob/master/deploy/v1/mpi-operator.yaml) and try the example again. Please let me know if v1 works in your environment.

**Comment by tingweiwu** [comment]
> Unfortunately, v2beta1 does not support elastic training, which we should make it clear to users. Please use [deploy file for v1](https://github.com/kubeflow/mpi-operator/blob/master/deploy/v1/mpi-operator.yaml) and try the example again. Please let me know if v1 works in your environment.

It works after redeploy v1 mpi-operator.yaml. it seems that  v2beta1 missed `slots` field in the `discover_hosts.sh`

Another question is launcher  did not start when the num of `Running` slots is bigger than the value  `min-np`

```
            command:
            - horovodrun
            args:
            - -np
            - "2"
            - --min-np
            - "1"
            - --max-np
            - "5"
            - --host-discovery-script
            - /etc/mpi/discover_hosts.sh
            - python
            - /examples/elastic/tensorflow2_mnist_elastic.py
```

```
tensorflow-mnist-elastic-2-launcher   0/1     Init:0/1    0          9m50s
tensorflow-mnist-elastic-2-worker-0   1/1     Running     0          9m50s
tensorflow-mnist-elastic-2-worker-1   1/1     Running     0          9m50s
tensorflow-mnist-elastic-2-worker-2   1/1     Running     0          9m50s
tensorflow-mnist-elastic-2-worker-3   0/1     Pending     0          9m50s
tensorflow-mnist-elastic-2-worker-4   0/1     Pending     0          9m50s
```

```
apiVersion: v1
data:
  discover_hosts.sh: |-
    #!/bin/sh
    echo tensorflow-mnist-elastic-2-worker-0:1
    echo tensorflow-mnist-elastic-2-worker-1:1
    echo tensorflow-mnist-elastic-2-worker-2:1
  hostfile: |
    tensorflow-mnist-elastic-2-worker-0 slots=1
    tensorflow-mnist-elastic-2-worker-1 slots=1
    tensorflow-mnist-elastic-2-worker-2 slots=1
    tensorflow-mnist-elastic-2-worker-3 slots=1
    tensorflow-mnist-elastic-2-worker-4 slots=1
  kubexec.sh: |-
    #!/bin/sh
    set -x
    POD_NAME=$1
    shift
    /opt/kube/kubectl exec ${POD_NAME} -- /bin/sh -c "$*"
kind: ConfigMap
metadata:
  creationTimestamp: "2021-12-07T11:54:49Z"
  labels:
    app: tensorflow-mnist-elastic-2
  name: tensorflow-mnist-elastic-2-config
  namespace: mpi-operator
  ownerReferences:
  - apiVersion: kubeflow.org/v1
    blockOwnerDeletion: true
    controller: true
    kind: MPIJob
    name: tensorflow-mnist-elastic-2
    uid: ef616a6e-bdbb-4a7d-8e72-cbed84e14f1b
  resourceVersion: "42354586"
  selfLink: /api/v1/namespaces/default/configmaps/tensorflow-mnist-elastic-2-config
  uid: 7a64b52b-9e86-42b7-812a-bb88614a73b8

```

**Comment by tingweiwu** [comment]
Another scene
1、I deploy `MPIJob` with Worker.replicas: 3， 
the training job start with 3 ranks
```
....
Tue Dec  7 12:39:18 2021[1]<stderr>:2021-12-07 12:39:18.924813: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Tue Dec  7 12:39:22 2021[2]<stdout>:Step #0     Loss: 2.122564
Tue Dec  7 12:39:22 2021[0]<stdout>:Step #0     Loss: 2.105374
Tue Dec  7 12:39:22 2021[1]<stdout>:Step #0     Loss: 2.158499
Tue Dec  7 12:39:24 2021[2]<stdout>:Step #10    Loss: 0.572109
Tue Dec  7 12:39:24 2021[1]<stdout>:Step #10    Loss: 0.599596
Tue Dec  7 12:39:24 2021[0]<stdout>:Step #10    Loss: 0.480093

...
```

2、kubectl edit mpijob tensorflow-mnist-elastic-2 , and modify Worker.replicas: 4 ` ,
the training job  change to 4 ranks

```
Tue Dec  7 12:41:26 2021[1]<stdout>:Step #470   Loss: 0.045115
Tue Dec  7 12:41:26 2021[2]<stdout>:Step #470   Loss: 0.064594
Tue Dec  7 12:41:26 2021[0]<stdout>:Step #470   Loss: 0.094789
Tue Dec  7 12:41:26 2021[3]<stderr>:+ POD_NAME=tensorflow-mnist-elastic-2-worker-3
Tue Dec  7 12:41:26 2021[3]<stderr>:+ shift
Tue Dec  7 12:41:26 2021[3]<stderr>:+ /opt/kube/kubectl exec tensorflow-mnist-elastic-2-worker-3 -- /bin/sh -c cd /examples > /dev/null 2>&1 ; HOROVOD_HOSTNAME=tensorflow-mnist-elastic-2-worker-3 HOROVOD_RANK=3 HOROVOD_SIZE=4 HOROVOD_LOCAL_RANK=0 HOROVOD_LOCAL_SIZE=1 HOROVOD_CROSS_RANK=3 HOROVOD_CROSS_SIZE=4  PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOSTNAME=tensorflow-mnist-elastic-2-launcher NVIDIA_DRIVER_CAPABILITIES='' OMPI_MCA_plm_rsh_agent=/etc/mpi/kubexec.sh OMPI_MCA_orte_default_hostfile=/etc/mpi/hostfile NVIDIA_VISIBLE_DEVICES='' KUBERNETES_SERVICE_PORT=443 KUBERNETES_SERVICE_PORT_HTTPS=443 KUBERNETES_PORT=tcp://10.247.0.1:443 KUBERNETES_PORT_443_TCP=tcp://10.247.0.1:443 KUBERNETES_PORT_443_TCP_PROTO=tcp KUBERNETES_PORT_443_TCP_PORT=443 KUBERNETES_PORT_443_TCP_ADDR=10.247.0.1 KUBERNETES_SERVICE_HOST=10.247.0.1 PAAS_POD_ID=70533cf1-245e-4a8c-9dee-3a7b0985956b TENSORFLOW_VERSION=2.3.0 PYTORCH_VERSION=1.6.0 TORCHVISION_VERSION=0.7.0 MXNET_VERSION=1.5.0 PYTHON_VERSION=3.7 HOME=/root LC_CTYPE=C.UTF-8 HOROVOD_STALL_CHECK_TIME_SECONDS=60 HOROVOD_STALL_SHUTDOWN_TIME_SECONDS=0 HOROVOD_NUM_NCCL_STREAMS=1 HOROVOD_CCL_BGT_AFFINITY=0 HOROVOD_GLOO_TIMEOUT_SECONDS=30 PYTHONUNBUFFERED=1 HOROVOD_GLOO_RENDEZVOUS_ADDR=10.140.0.138 HOROVOD_GLOO_RENDEZVOUS_PORT=28386 HOROVOD_CONTROLLER=gloo HOROVOD_CPU_OPERATIONS=gloo HOROVOD_GLOO_IFACE=eth0 NCCL_SOCKET_IFNAME=eth0 HOROVOD_ELASTIC=1 python /examples/elastic/tensorflow2_mnist_elastic.py
Tue Dec  7 12:41:32 2021[3]<stdout>:Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
Tue Dec  7 12:41:33 2021[3]<stdout>:^MTue Dec  7 12:41:33 2021[3]<stdout>:    8192/11490434 [..............................] - ETA: 4s^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^MTue Dec  7 12:41:33 2021[3]<stdout>:   24576/11490434 [..............................] - ETA: 28s^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^MTue Dec  7 12:41:33 2021[3]<stdout>:   57344/11490434 [..............................] - ETA: 22s^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^MTue Dec  7 12:41:33 2021[3]<stdout>:  114688/11490434 [..............................] - ETA: 16s^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^MTue Dec  7 12:41:33 2021[3]<stdout>:  221184/11490434 [..............................] - ETA: 10s^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^MTue Dec  7 12:41:33 2021[3]<stdout>:  401408/11490434 [>.............................] - ETA: 7s ^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^MTue Dec  7 12:41:33 2021[3]<stdout>:  745472/11490434 [>.............................] - ETA: 4s^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^MTue Dec  7 12:41:33 2021[3]<stdout>: 1392640/11490434 [==>...........................] - ETA: 2s^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^MTue Dec  7 12:41:33 2021[3]<stdout>: 2605056/11490434 [=====>........................] - ETA: 1s^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^MTue Dec  7 12:41:33 2021[3]<stdout>: 3964928/11490434 [=========>....................] - ETA: 0s^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^MTue Dec  7 12:41:34 2021[3]<stdout>: 5341184/11490434 [============>.................] - ETA: 0s^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^MTue Dec  7 12:41:34 2021[3]<stdout>: 6717440/11490434 [================>.............] - ETA: 0s^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^MTue Dec  7 12:41:34 2021[3]<stdout>: 8192000/11490434 [====================>.........] - ETA: 0s^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^MTue Dec  7 12:41:34 2021[3]<stdout>: 9650176/11490434 [========================>.....] - ETA: 0s^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^MTue Dec  7 12:41:34 2021[3]<stdout>:11026432/11490434 [===========================>..] - ETA: 0s^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^MTue Dec  7 12:41:34 2021[3]<stdout>:11493376/11490434 [==============================] - 1s 0us/step
Tue Dec  7 12:41:34 2021[3]<stderr>:2021-12-07 12:41:34.730569: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
Tue Dec  7 12:41:34 2021[3]<stderr>:To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Tue Dec  7 12:41:34 2021[3]<stderr>:2021-12-07 12:41:34.750455: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2600000000 Hz
Tue Dec  7 12:41:34 2021[3]<stderr>:2021-12-07 12:41:34.751437: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x36b4580 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
Tue Dec  7 12:41:34 2021[3]<stderr>:2021-12-07 12:41:34.751465: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Tue Dec  7 12:41:40 2021[1]<stdout>:Step #480   Loss: 0.032260
Tue Dec  7 12:41:40 2021[2]<stdout>:Step #480   Loss: 0.021865
Tue Dec  7 12:41:40 2021[3]<stdout>:Step #480   Loss: 0.057452
Tue Dec  7 12:41:40 2021[0]<stdout>:Step #480   Loss: 0.087563

```

3、kubectl edit mpijob tensorflow-mnist-elastic-2 , and modify Worker.replicas: 3 ` 
the training job change back to 3 ranks
```
Tue Dec  7 12:44:45 2021[1]<stdout>:Step #1170  Loss: 0.010245
Tue Dec  7 12:44:45 2021[2]<stdout>:Step #1170  Loss: 0.051376
Tue Dec  7 12:44:45 2021[3]<stdout>:Step #1170  Loss: 0.058886
Tue Dec  7 12:44:45 2021[0]<stdout>:Step #1170  Loss: 0.004547
Tue Dec  7 12:44:45 2021[2]<stderr>:[2021-12-07 12:44:45.326530: E /tmp/pip-install-2jy0u7mn/horovod/horovod/common/operations.cc:525] Horovod background loop uncaught exception: [/tmp/pip-install-2jy0u7mn/horovod/third_party/compatible_gloo/gloo/transport/tcp/pair.cc:566] Read error [10.140.0.107]:12416: Connection reset by peer
Tue Dec  7 12:44:45 2021[0]<stderr>:[2021-12-07 12:44:45.326489: E /tmp/pip-install-2jy0u7mn/horovod/horovod/common/operations.cc:525] Horovod background loop uncaught exception: [/tmp/pip-install-2jy0u7mn/horovod/third_party/compatible_gloo/gloo/transport/tcp/pair.cc:566] Read error [10.140.0.107]:17321: Connection reset by peer
Tue Dec  7 12:44:45 2021[3]<stderr>:command terminated with exit code 137
Tue Dec  7 12:44:45 2021[1]<stderr>:[2021-12-07 12:44:45.351779: E /tmp/pip-install-2jy0u7mn/horovod/horovod/common/operations.cc:525] Horovod background loop uncaught exception: [/tmp/pip-install-2jy0u7mn/horovod/third_party/compatible_gloo/gloo/transport/tcp/pair.cc:575] Connection closed by peer [10.140.0.127]:2212
WARNING:root:blacklist failing host: tensorflow-mnist-elastic-2-worker-3
Process 3 exit with status code 137.
Tue Dec  7 12:44:46 2021[2]<stdout>:Step #1170  Loss: 0.030425
Tue Dec  7 12:44:46 2021[1]<stdout>:Step #1170  Loss: 0.010394
Tue Dec  7 12:44:46 2021[0]<stdout>:Step #1170  Loss: 0.027107

```
4、kubectl edit mpijob tensorflow-mnist-elastic-2 , and modify Worker.replicas: 5 `
the 5th pod is Pending and the horovod training job don't change to 4 ranks 
```
tensorflow-mnist-elastic-2-launcher   1/1     Running     0          16m
tensorflow-mnist-elastic-2-worker-0   1/1     Running     0          16m
tensorflow-mnist-elastic-2-worker-1   1/1     Running     0          16m
tensorflow-mnist-elastic-2-worker-2   1/1     Running     0          16m
tensorflow-mnist-elastic-2-worker-3   1/1     Running     0          9m42s
tensorflow-mnist-elastic-2-worker-4   0/1     Pending     0          9m42s
```
Is there any mechanism cause this when there is a Pending  pod?

**Comment by zw0610** [comment]
> Another question is launcher did not start when the num of Running slots is bigger than the value min-np

Exactly. However, the `min-np` is specified as args or commands or entrypoint embedded in training image, which mpi-operator cannot determine. So for mpi-operator, it will still check if number of workers specified in `replicas` is fully running and then start the launcher pod.

-----
For the 5th pod issue, I will check how this happens. But the fix may filed in the https://github.com/kubeflow/training-operator repo as v1 controller is just migrated there. I will definitely keep you updated.

**Comment by zw0610** [comment]
> 3、kubectl edit mpijob tensorflow-mnist-elastic-2 , and modify Worker.replicas: 3 `
the training job change back to 3 ranks

Could you confirm the pods status (`kubectl get po`) when worker replicas is backing to 3? Meanwhile, could you let us know the pods status when apply the change of replicas from 3 to 4? It may be the `tensorflow-mnist-elastic-2-worker-3    ` is in terminating while the replicas is scale back to 4, which we still consider as a bug.

> 4、kubectl edit mpijob tensorflow-mnist-elastic-2 , and modify Worker.replicas: 5 `
the 5th pod is Pending and the horovod training job don't change to 4 ranks

I try to reproduce the issue with mpi-operator at master branch but failed as I didn't see the 5th pod. Could you confirm it's reproducible and share the log of mpi-operator with us?

**Comment by alculquicondor** [comment]
> It works after redeploy v1 mpi-operator.yaml. it seems that v2beta1 missed slots field in the discover_hosts.sh

The slots were replaced by a environment variable in v2, as it simplified the support of Intel. I was not aware that this was necessary for horovod to do elastic resize.

Happy to review a fix. But I would also ask the contributor to add an E2E test for future proofing.

**Comment by alculquicondor** [comment]
Opened #445 for tracking.

**Comment by tingweiwu** [comment]
> > 3、kubectl edit mpijob tensorflow-mnist-elastic-2 , and modify Worker.replicas: 3 `
> > the training job change back to 3 ranks
> 
> Could you confirm the pods status (`kubectl get po`) when worker replicas is backing to 3? Meanwhile, could you let us know the pods status when apply the change of replicas from 3 to 4? It may be the `tensorflow-mnist-elastic-2-worker-3 ` is in terminating while the replicas is scale back to 4, which we still consider as a bug.
> 
> > 4、kubectl edit mpijob tensorflow-mnist-elastic-2 , and modify Worker.replicas: 5 `
> > the 5th pod is Pending and the horovod training job don't change to 4 ranks
> 
> I try to reproduce the issue with mpi-operator at master branch but failed as I didn't see the 5th pod. Could you confirm it's reproducible and share the log of mpi-operator with us?

this is the pod status  and logs in step2 , edit replicas from 3 to 4.
```
tensorflow-mnist-elastic-2-launcher   1/1     Running     0          2m53s
tensorflow-mnist-elastic-2-worker-0   1/1     Running     0          2m54s
tensorflow-mnist-elastic-2-worker-1   1/1     Running     0          2m54s
tensorflow-mnist-elastic-2-worker-2   1/1     Running     0          2m54s
tensorflow-mnist-elastic-2-worker-3   1/1     Running     0          73s

....
Wed Dec  8 02:01:36 2021[1]<stdout>:Step #480	Loss: 0.161612
Wed Dec  8 02:01:36 2021[2]<stdout>:Step #480	Loss: 0.047648
Wed Dec  8 02:01:36 2021[0]<stdout>:Step #480	Loss: 0.029899
Wed Dec  8 02:01:38 2021[3]<stderr>:+ POD_NAME=tensorflow-mnist-elastic-2-worker-3
Wed Dec  8 02:01:38 2021[3]<stderr>:+ shift
Wed Dec  8 02:01:38 2021[3]<stderr>:+ /opt/kube/kubectl exec tensorflow-mnist-elastic-2-worker-3 -- /bin/sh -c cd /examples > /dev/null 2>&1 ; HOROVOD_HOSTNAME=tensorflow-mnist-elastic-2-worker-3 HOROVOD_RANK=3 HOROVOD_SIZE=4 HOROVOD_LOCAL_RANK=0 HOROVOD_LOCAL_SIZE=1 HOROVOD_CROSS_RANK=3 HOROVOD_CROSS_SIZE=4  PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOSTNAME=tensorflow-mnist-elastic-2-launcher NVIDIA_DRIVER_CAPABILITIES='' OMPI_MCA_plm_rsh_agent=/etc/mpi/kubexec.sh OMPI_MCA_orte_default_hostfile=/etc/mpi/hostfile NVIDIA_VISIBLE_DEVICES='' KUBERNETES_SERVICE_PORT=443 KUBERNETES_SERVICE_PORT_HTTPS=443 KUBERNETES_PORT=tcp://10.247.0.1:443 KUBERNETES_PORT_443_TCP=tcp://10.247.0.1:443 KUBERNETES_PORT_443_TCP_PROTO=tcp KUBERNETES_PORT_443_TCP_PORT=443 KUBERNETES_PORT_443_TCP_ADDR=10.247.0.1 KUBERNETES_SERVICE_HOST=10.247.0.1 PAAS_POD_ID=775c2747-e76f-4f2f-b553-5dd1b19603c8 TENSORFLOW_VERSION=2.3.0 PYTORCH_VERSION=1.6.0 TORCHVISION_VERSION=0.7.0 MXNET_VERSION=1.5.0 PYTHON_VERSION=3.7 HOME=/root LC_CTYPE=C.UTF-8 HOROVOD_STALL_CHECK_TIME_SECONDS=60 HOROVOD_STALL_SHUTDOWN_TIME_SECONDS=0 HOROVOD_NUM_NCCL_STREAMS=1 HOROVOD_CCL_BGT_AFFINITY=0 HOROVOD_GLOO_TIMEOUT_SECONDS=30 PYTHONUNBUFFERED=1 HOROVOD_GLOO_RENDEZVOUS_ADDR=10.140.0.140 HOROVOD_GLOO_RENDEZVOUS_PORT=5024 HOROVOD_CONTROLLER=gloo HOROVOD_CPU_OPERATIONS=gloo HOROVOD_GLOO_IFACE=eth0 NCCL_SOCKET_IFNAME=eth0 HOROVOD_ELASTIC=1 python /examples/elastic/tensorflow2_mnist_elastic.py
Wed Dec  8 02:01:45 2021[3]<stdout>:Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
Wed Dec  8 02:01:46 2021[3]<stdout>:11493376/11490434 [==============================] - 1s 0us/step
Wed Dec  8 02:01:47 2021[3]<stderr>:2021-12-08 02:01:47.319087: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
Wed Dec  8 02:01:47 2021[3]<stderr>:To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Wed Dec  8 02:01:47 2021[3]<stderr>:2021-12-08 02:01:47.336220: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2600000000 Hz
Wed Dec  8 02:01:47 2021[3]<stderr>:2021-12-08 02:01:47.337290: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3987170 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
Wed Dec  8 02:01:47 2021[3]<stderr>:2021-12-08 02:01:47.337327: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Wed Dec  8 02:01:50 2021[1]<stdout>:Step #490	Loss: 0.102496
Wed Dec  8 02:01:50 2021[2]<stdout>:Step #490	Loss: 0.037276
Wed Dec  8 02:01:50 2021[0]<stdout>:Step #490	Loss: 0.025020
Wed Dec  8 02:01:50 2021[3]<stdout>:Step #490	Loss: 0.128833

```
then in step3 , edit replicas from 4 to 3. the  `tensorflow-mnist-elastic-2-worker-3` terminating state is temporary
```
tensorflow-mnist-elastic-2-launcher   1/1     Running     0          4m28s
tensorflow-mnist-elastic-2-worker-0   1/1     Running     0          4m29s
tensorflow-mnist-elastic-2-worker-1   1/1     Running     0          4m29s
tensorflow-mnist-elastic-2-worker-2   1/1     Running     0          4m29s

Wed Dec  8 02:03:08 2021[1]<stdout>:Step #780	Loss: 0.010922
Wed Dec  8 02:03:08 2021[3]<stdout>:Step #780	Loss: 0.038819
Wed Dec  8 02:03:08 2021[0]<stdout>:Step #780	Loss: 0.062027
Wed Dec  8 02:03:08 2021[2]<stdout>:Step #780	Loss: 0.008519
Wed Dec  8 02:03:09 2021[2]<stderr>:[2021-12-08 02:03:09. 24079: E /tmp/pip-install-2jy0u7mn/horovod/horovod/common/operations.cc:525] Horovod background loop uncaught exception: [/tmp/pip-install-2jy0u7mn/horovod/third_party/compatible_gloo/gloo/transport/tcp/pair.cc:566] Read error [10.140.0.99]:60044: Connection reset by peer
Wed Dec  8 02:03:09 2021[3]<stderr>:command terminated with exit code 137
Wed Dec  8 02:03:09 2021[1]<stderr>:[2021-12-08 02:03:09. 44198: E /tmp/pip-install-2jy0u7mn/horovod/horovod/common/operations.cc:525] Horovod background loop uncaught exception: [/tmp/pip-install-2jy0u7mn/horovod/third_party/compatible_gloo/gloo/transport/tcp/pair.cc:575] Connection closed by peer [10.140.0.124]:22198
Wed Dec  8 02:03:09 2021[0]<stderr>:[2021-12-08 02:03:09. 53998: E /tmp/pip-install-2jy0u7mn/horovod/horovod/common/operations.cc:525] Horovod background loop uncaught exception: [/tmp/pip-install-2jy0u7mn/horovod/third_party/compatible_gloo/gloo/transport/tcp/pair.cc:575] Connection closed by peer [10.140.0.127]:36028
WARNING:root:blacklist failing host: tensorflow-mnist-elastic-2-worker-3
Process 3 exit with status code 137.
Wed Dec  8 02:03:12 2021[1]<stdout>:Step #790	Loss: 0.110239
Wed Dec  8 02:03:12 2021[2]<stdout>:Step #790	Loss: 0.051231
Wed Dec  8 02:03:12 2021[0]<stdout>:Step #790	Loss: 0.041764



```
the pod status in step 4
```
tensorflow-mnist-elastic-2-launcher   1/1     Running     0          5m49s
tensorflow-mnist-elastic-2-worker-0   1/1     Running     0          5m50s
tensorflow-mnist-elastic-2-worker-1   1/1     Running     0          5m50s
tensorflow-mnist-elastic-2-worker-2   1/1     Running     0          5m50s
tensorflow-mnist-elastic-2-worker-3   1/1     Running     0          34s
tensorflow-mnist-elastic-2-worker-4   0/1     Pending     0          34s


```
 error logs about `tensorflow-mnist-elastic-2-worker-4` in mpi-operator  
```
E1208 02:04:14.431195       1 mpi_job_controller.go:426] error syncing 'default/tensorflow-mnist-elastic-2': pods "tensorflow-mnist-elastic-2-worker-4" already exists
I1208 02:04:14.431263       1 event.go:258] Event(v1.ObjectReference{Kind:"MPIJob", Namespace:"default", Name:"tensorflow-mnist-elastic-2", UID:"19639104-89a7-4568-a973-3352889e894b", APIVersion:"kubeflow.org/v1", ResourceVersion:"42637359", FieldPath:""}): type: 'Warning' reason: 'MPIJobFailed' worker pod created failed: pods "tensorflow-mnist-elastic-2-worker-4" already exists

```

**Comment by tingweiwu** [comment]
[mpi-operator.log](https://github.com/kubeflow/mpi-operator/files/7672796/mpi-operator.log)

**Comment by tingweiwu** [comment]
> Exactly. However, the `min-np` is specified as args or commands or entrypoint embedded in training image, which mpi-operator cannot determine. So for mpi-operator, it will still check if number of workers specified in `replicas` is fully running and then start the launcher pod.

Will you consider adding min-replicas into mpi-operator to check the min running workers instead of fully

**Comment by zw0610** [comment]
> Will you consider adding min-replicas into mpi-operator to check the min running workers instead of fully

Yes. We just added similar feature to PyTorchJob in training-operator by adding a special field called [`ElasticPolicy`](https://github.com/kubeflow/training-operator/blob/master/pkg/apis/pytorch/v1/types.go#L66). We are considering adding such feature to all other elastic-compatible APIs including MPIJob and TFJob.

**Comment by zw0610** [comment]
@tingweiwu Could you consider adding my WeChat (Zhang_Wang) so we can locate the issue as I was not able to reproduce it by myself?
